# Generated by Django 4.1 on 2024-06-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="subject",
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
